with
    MAIN as (
        select
            T2.COMPANY_ID,
            T1.CARDUP_PAYMENT_PAYMENT_TYPE,
            T2.CLUSTER_KMEANS,
            COUNT(DWH_CARDUP_PAYMENT_ID) COUNT_TX,
            SUM(CARDUP_PAYMENT_USD_AMT) SUM_TX
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
            join DEV.SBOX_SHILTON.TEST_CLUSTERING_RESULTS T2 on T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID = T2.COMPANY_ID
        where
            true
            -- and CLUSTER_KMEANS = 2
            and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= DATE('2023-09-01')
            and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
            and CARDUP_PAYMENT_PAYMENT_TYPE = 'GST'
        group by
            1,
            2,
            3
    )
select
    COMPANY_ID,
    CLUSTER_KMEANS,
    APPROX_PERCENTILE(SUM_TX, 0.5),
    APPROX_PERCENTILE(COUNT_TX, 0.5)
from
    MAIN
group by
    1,
    2;

--count etc by calendar date
select
    TO_CHAR(DATE_TRUNC(day, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'DD-MON'),
    CLUSTER_KMEANS,
    COUNT(distinct CARDUP_PAYMENT_CUSTOMER_COMPANY_ID),
    COUNT(distinct DWH_CARDUP_PAYMENT_ID),
    SUM(CARDUP_PAYMENT_USD_AMT)
from
    ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
    join DEV.SBOX_SHILTON.TEST_CLUSTERING_RESULTS T2 on T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID = T2.COMPANY_ID
where
    true
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= DATE('2023-09-01')
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
    and CARDUP_PAYMENT_PAYMENT_TYPE = 'GST'
group by
    1,
    2;

--count tx in 2 year by customer
select
    CARDUP_PAYMENT_CUSTOMER_COMPANY_ID,
    CLUSTER_KMEANS,
    COUNT(distinct DWH_CARDUP_PAYMENT_ID),
    SUM(CARDUP_PAYMENT_USD_AMT)
from
    ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
    join DEV.SBOX_SHILTON.TEST_CLUSTERING_RESULTS T2 on T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID = T2.COMPANY_ID
where
    true
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= DATE('2023-09-01')
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
    and CARDUP_PAYMENT_PAYMENT_TYPE = 'GST'
group by
    1,
    2;

select
    T1.C1 COMPANY_ID,
    SUM(CARDUP_PAYMENT_NET_REVENUE_USD_AMT) TOTAL_NET_REV_USD,
    SUM(CARDUP_PAYMENT_TOTAL_REVENUE_USD_AMT) TOTAL_REV_USD,
    SUM(CARDUP_PAYMENT_CARDUP_FEE) TOTAL_CARDUP_FEE_LCL,
    SUM(CARDUP_PAYMENT_LCL_AMT) TOTAL_GTV_LCL
from
    DEV.SBOX_SHILTON.MARKETING_IDS_UNMANAGED T1
    join ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T2 on T1.C1 = T2.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID
group by
    1;

--count etc by calendar date, hvc
with
    RECENCY as (
        select
            T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID COMPANY_ID,
            MAX(DATE('2024-09-01')) - MAX(DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) DAYS_SINCE_LAST_TX,
            MAX(DATE('2024-09-01')) - MIN(DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) DAYS_SINCE_FIRST_TX
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
            join (
                select
                    COMPANY_ID
                from
                    DEV.SBOX_SHILTON.CARDUP_USER_MANAGED_UNMANAGED
                where
                    OWNER = 'Unmanaged'
            ) T2 on T2.COMPANY_ID = T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID
        WHERE
            CARDUP_PAYMENT_STATUS NOT IN ('Payment Failed', 'Cancelled', 'Refunded', 'Refunding')
            AND CARDUP_PAYMENT_USER_TYPE IN ('business', 'guest')
            and CARDUP_PAYMENT_CU_LOCALE_ID = 1
            -- and date(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= date('2023-09-01')
            and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
        group by
            1
    )
select
    -- TO_CHAR(DATE_TRUNC(day, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'DD-MON'),
    TO_CHAR(DATE_TRUNC(day, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'DD'),
    -- TO_CHAR(DATE_TRUNC(month, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'MON-YYYY'),
    CLUSTER_KMEANS,
    CARDUP_PAYMENT_PAYMENT_TYPE,
    COUNT(distinct CARDUP_PAYMENT_CUSTOMER_COMPANY_ID),
    COUNT(distinct DWH_CARDUP_PAYMENT_ID),
    SUM(CARDUP_PAYMENT_USD_AMT)
from
    ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
    join DEV.SBOX_SHILTON.TEST_CLUSTERING_RESULTS T2 on T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID = T2.COMPANY_ID
    left outer join RECENCY T3 on T3.COMPANY_ID = T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID
where
    true
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= DATE('2023-09-01')
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
    and CLUSTER_KMEANS = 2
    and DAYS_SINCE_FIRST_TX>=365
group by
    1,
    2,
    3;

--count etc by calendar date, hvc, totals
with
    RECENCY as (
        select
            T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID COMPANY_ID,
            MAX(DATE('2024-09-01')) - MAX(DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) DAYS_SINCE_LAST_TX,
            MAX(DATE('2024-09-01')) - MIN(DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) DAYS_SINCE_FIRST_TX
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
            join (
                select
                    COMPANY_ID
                from
                    DEV.SBOX_SHILTON.CARDUP_USER_MANAGED_UNMANAGED
                where
                    OWNER = 'Unmanaged'
            ) T2 on T2.COMPANY_ID = T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID
        WHERE
            CARDUP_PAYMENT_STATUS NOT IN ('Payment Failed', 'Cancelled', 'Refunded', 'Refunding')
            AND CARDUP_PAYMENT_USER_TYPE IN ('business', 'guest')
            and CARDUP_PAYMENT_CU_LOCALE_ID = 1
            -- and date(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= date('2023-09-01')
            and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
        group by
            1
    )
select
    -- TO_CHAR(DATE_TRUNC(day, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'DD-MON'),
    -- TO_CHAR(DATE_TRUNC(day, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'DD'),
    -- TO_CHAR(DATE_TRUNC(month, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'MM'),
    CLUSTER_KMEANS,
    CARDUP_PAYMENT_PAYMENT_TYPE,
    ROUND(DAYS_SINCE_FIRST_TX / 365),
    COUNT(distinct CARDUP_PAYMENT_CUSTOMER_COMPANY_ID),
    COUNT(distinct DWH_CARDUP_PAYMENT_ID),
    SUM(CARDUP_PAYMENT_USD_AMT)
from
    ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
    join DEV.SBOX_SHILTON.TEST_CLUSTERING_RESULTS T2 on T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID = T2.COMPANY_ID
    left outer join RECENCY T3 on T3.COMPANY_ID = T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID
where
    true
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= DATE('2023-09-01')
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
    and CLUSTER_KMEANS = 2
group by
    1,
    2,
    3;


--count etc by calendar date, hvc
with
    RECENCY as (
        select
            T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID COMPANY_ID,
            MAX(DATE('2024-09-01')) - MAX(DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) DAYS_SINCE_LAST_TX,
            MAX(DATE('2024-09-01')) - MIN(DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) DAYS_SINCE_FIRST_TX,
            count(distinct DWH_CARDUP_PAYMENT_ID) COUNT_TX
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
            join (
                select
                    COMPANY_ID
                from
                    DEV.SBOX_SHILTON.CARDUP_USER_MANAGED_UNMANAGED
                where
                    OWNER = 'Unmanaged'
            ) T2 on T2.COMPANY_ID = T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID
        WHERE
            CARDUP_PAYMENT_STATUS NOT IN ('Payment Failed', 'Cancelled', 'Refunded', 'Refunding')
            AND CARDUP_PAYMENT_USER_TYPE IN ('business', 'guest')
            and CARDUP_PAYMENT_CU_LOCALE_ID = 1
            -- and date(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= date('2023-09-01')
            and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
            and CARDUP_PAYMENT_PAYMENT_TYPE='Supplier'
        group by
            1
    )
select
    -- TO_CHAR(DATE_TRUNC(day, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'DD-MON'),
    -- TO_CHAR(DATE_TRUNC(day, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'DD'),
    -- TO_CHAR(DATE_TRUNC(month, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'MON-YYYY'),
    TO_CHAR(DATE_TRUNC(month, DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)), 'MM'),
    CLUSTER_KMEANS,
    CARDUP_PAYMENT_PAYMENT_TYPE,
    -- cardup_payment_schedule_type,
    -- round(COUNT_TX/(DAYS_SINCE_FIRST_TX/30)) MONTHLY_TX_COUNT,
    COUNT(distinct CARDUP_PAYMENT_CUSTOMER_COMPANY_ID),
    COUNT(distinct DWH_CARDUP_PAYMENT_ID),
    SUM(CARDUP_PAYMENT_USD_AMT)
from
    ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T T1
    join DEV.SBOX_SHILTON.TEST_CLUSTERING_RESULTS T2 on T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID = T2.COMPANY_ID
    left outer join RECENCY T3 on T3.COMPANY_ID = T1.CARDUP_PAYMENT_CUSTOMER_COMPANY_ID
where
    true
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) >= DATE('2021-09-01')
    and DATE(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) <= DATE('2024-08-31')
    and CLUSTER_KMEANS = 2
    and DAYS_SINCE_FIRST_TX>=365
    -- and CARDUP_PAYMENT_PAYMENT_TYPE='Supplier'
group by
    1,
    2,
    3;

